// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.     
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Diagnostics.CodeAnalysis;

namespace DoctorVanGogh.ModSwitch {
    [GeneratedCode("DefGenerator.tt","0.1")]
    [SuppressMessage("ReSharper", "InconsistentNaming")]
    [SuppressMessage("ReSharper", "UnusedMember.Global")]
	public static partial class LanguageKeys {
		public static class @keyed {
			/// <summary>
			/// Get's the translation key for '<em>ModSwitch</em>'
			/// </summary>
			public const string @ModSwitch = "ModSwitch";
			/// <summary>
			/// Get's the translation key for '<em>Save current mod set</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Create = "ModSwitch.Tip.Create";
			/// <summary>
			/// Get's the translation key for '<em>Delete</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Delete = "ModSwitch.Tip.Delete";
			/// <summary>
			/// Get's the translation key for '<em>Rename</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Rename = "ModSwitch.Tip.Rename";
			/// <summary>
			/// Get's the translation key for '<em>Settings</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Settings = "ModSwitch.Tip.Settings";
			/// <summary>
			/// Get's the translation key for '<em>Undo</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Undo = "ModSwitch.Tip.Undo";
			/// <summary>
			/// Get's the translation key for '<em>Apply mod set</em>'
			/// </summary>
			public const string @ModSwitch_Tip_Apply = "ModSwitch.Tip.Apply";
			/// <summary>
			/// Get's the translation key for '<em>Import</em>'
			/// </summary>
			public const string @ModSwitch_Import = "ModSwitch.Import";
			/// <summary>
			/// Get's the translation key for '<em>{0} items</em>'
			/// </summary>
			public const string @ModSwitch_ModSet_Mods = "ModSwitch.ModSet.Mods";
			/// <summary>
			/// Get's the translation key for '<em>Really delete <em>'{0}'</em>?</em>'
			/// </summary>
			public const string @ModSwitch_ModSet_ConfirmDelete = "ModSwitch.ModSet.ConfirmDelete";
			/// <summary>
			/// Get's the translation key for '<em>Confirmation needed</em>'
			/// </summary>
			public const string @ModSwitch_Confirmation_Title = "ModSwitch.Confirmation.Title";
			/// <summary>
			/// Get's the translation key for '<em>Missing mods</em>'
			/// </summary>
			public const string @ModSwitch_MissingMods_Title = "ModSwitch.MissingMods.Title";
			/// <summary>
			/// Get's the translation key for '<em>New mod set</em>'
			/// </summary>
			public const string @ModSwitch_Create_DefaultName = "ModSwitch.Create.DefaultName";
			/// <summary>
			/// Get's the translation key for '<em>Do you want to append the imported sets or replace all existing sets?</em>'
			/// </summary>
			public const string @ModSwitch_Import_Text = "ModSwitch.Import.Text";
			/// <summary>
			/// Get's the translation key for '<em>Replace</em>'
			/// </summary>
			public const string @ModSwitch_Import_Choice_Replace = "ModSwitch.Import.Choice.Replace";
			/// <summary>
			/// Get's the translation key for '<em>Append</em>'
			/// </summary>
			public const string @ModSwitch_Import_Choice_Append = "ModSwitch.Import.Choice.Append";
		}
	}
}
